redis:
        host: localhost
        port: 6379

token: bot_token

database:
  user: username
  pass: password
  host: localhost
  port: 3306
  dbname: databasename
  quries:
    myquery: select * from mytable
